// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihhgkkxwsntpeqbduzhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloaGdra3h3c250cGVxYmR1emhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzAzOTAsImV4cCI6MjA2MjgwNjM5MH0.qQoVJfJrXpKghfsCVGQKpYa9IVTNZH5SE7uS_qSaO6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);